on: [push]
name: CI
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    strategy:
      matrix:
        go-version: [1.21.x]

    runs-on: ubuntu-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: Install ONNX
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config wget tree
        OV=1.20.1
        ARCH="x64"
        wget https://github.com/microsoft/onnxruntime/releases/download/v${OV}/onnxruntime-linux-${ARCH}-${OV}.tgz
        tar xf onnxruntime-linux-${ARCH}-${OV}.tgz
        sudo mv onnxruntime-linux-${ARCH}-${OV} /usr/local/onnxruntime
        sudo mkdir -p /usr/local/share/pkgconfig
        sudo cp /usr/local/onnxruntime/lib/pkgconfig/libonnxruntime.pc /usr/local/share/pkgconfig/
        sudo sed -i "s/\/usr\/local/\/usr\/local\/onnxruntime/g" /usr/local/share/pkgconfig/libonnxruntime.pc
        sudo sed -i "s/\/lib64/\/lib/g" /usr/local/share/pkgconfig/libonnxruntime.pc
        sudo sed -i "s/\/include\/onnxruntime/\/include/g" /usr/local/share/pkgconfig/libonnxruntime.pc
        echo "/usr/local/onnxruntime/lib" | sudo tee /etc/ld.so.conf.d/libonnxruntime.conf
        sudo ldconfig
    - name: Execute Tests
      run: |
        go mod download
        go mod verify
        make test
      env:
        CI: true
