name: golangci-lint
on: [push]
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    strategy:
      matrix:
        go-version: [1.21.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install ONNX
        run: |
          apt-get update
          apt-get install -y pkg-config wget
          OV=1.20.1
          ARCH="x64"
          wget https://github.com/microsoft/onnxruntime/releases/download/v${OV}/onnxruntime-linux-${ARCH}-${OV}.tgz
          tar xf onnxruntime-linux-${ARCH}-${OV}.tgz
          mv onnxruntime-linux-${ARCH}-${OV} /usr/local/onnxruntime
          mkdir -p /usr/local/share/pkgconfig
          cp /usr/local/onnxruntime/lib/pkgconfig/libonnxruntime.pc /usr/local/share/pkgconfig/
          sed -i "s/\/usr\/local/\/usr\/local\/onnxruntime/g" /usr/local/share/pkgconfig/libonnxruntime.pc
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.57.2
